<?xml version="1.0" encoding="utf-8"?><Database Name="FDA_MARIJUANA" Class="LINQ_MAREJUANADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.81;Initial Catalog=FDA_MARIJUANA;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FDA_MARIJUANAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MARIJUANA" Member="MARIJUANAs">
    <Type Name="MARIJUANA">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="year" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcnno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_THAIFULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ROAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_THMBL_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_AMPHR_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_CHWNGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_TELEPHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_EMAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thanameplace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thaaddr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thasoi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_tharoad" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thamu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thathmblnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thaamphrnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thachngwtnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_tel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_fax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engaddr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_tharoom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thafloor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thabuilding" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engsoi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engroad" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_TYPE" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_TYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_zipcode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engmu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engfloor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engbuilding" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engnameplace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_HOUSENO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_Branch" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_LOCATION_TYPE_NORMAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_LOCATION_TYPE_OTHER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_LOCATION_TYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_SYSTEM_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_thmblcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_chngwtcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engthmblnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engamphrnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_engchngwtnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BSN_THAINAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_THAILASTNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_PREFIXENGCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ENGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ENGLASTNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ENGFULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CHANGWAT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMPHR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TUMBON_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BSN_FLOOR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_BUILDING" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ZIPCODE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NATIONALITY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_HOUSENO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ENGADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ENGMU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ENGSOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_ENGROAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_CHWNG_ENGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_AMPHR_ENGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_THMBL_ENGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_NATIONALITY_CD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="prefixcd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_amphrcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BSN_PREFIXTHAICD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LICENSED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NUM_IN_YEAR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVDATE_DISPLAY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Producer_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CANCEL_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CANCEL_DATE_DISPLAY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LCNNO_DISPLAY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BSN_PREFIXNAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WORKING_USER_TYPE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="PurposeName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SubPurpose" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="InSubPurpose" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Co_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_Name_Gov" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_Name_School" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_Id" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Co_PlaceName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Co_HouseCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_LocationNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_Soi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_Road" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_Moo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_ProvinceId" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Co_DistrictId" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Co_SubDistrictId" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Co_Province" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_District" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_SubDistrict" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co_PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Co_Tel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Co_Fax" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Co_Email" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Co_Flag" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Legal_HouseCode" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Score" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ScoreResult" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LCN_THAIFULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ROAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_THMBL_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_AMPHR_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_CHWNGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_TELEPHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_EMAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCN_THAINAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_THAILASTNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_PREFIXENGCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGLASTNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGFULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_FLOOR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_BUILDING" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ZIPCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_HOUSENO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGMU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGSOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGROAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_CHWNG_ENGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_AMPHR_ENGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_THMBL_ENGNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_NATIONALITY_CD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_PREFIXTHAICD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_PREFIXNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_BIRTH_DAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BSN_AGE_YEAR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BSN_AGE_MONTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContractNo_SubPurpose" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContractDMY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContractStartDt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContractEndDt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProjectName_Purpose" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Manage_Modern" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Manage_Traditional" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Manage_Herb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Education_Doctor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Education_LocalDoctor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Education_Modern" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Education_Traditional" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Education_Herb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Production_Licensee" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Production_Modern" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Production_Traditional" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Production_Herb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Plant_Patient_Modern" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequesterType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Sale_Patient_Licensee" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Sale_Patient_Doctor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Sale_Patient_LocalDoctor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Sale_Education_Doctor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Sale_Education_Traditional" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Sale_Agricultural" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Sale_Agricultural_Licensee" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Plant_Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform_Manage_Modern" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform_Manage_Traditional" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform__Manage_Herb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform__Education_Doctor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform__Education_LocalDoctor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform__Education_Modern" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform__Education_Traditional" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform__Education_Herb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform__Production_Licensee" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform_Production_Modern" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform_Production_Traditional" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform_Production_Herb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Transform_Patient_Modern" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenseNo_Cook_Requester" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_BY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FIRST_CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FIRST_CONSIDER_DATE_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EXP_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EXP_DATE_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="APPROVE_BY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VISITOR_ID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="VISITOR_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CASEs" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="REMARK_NOTE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dataFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_DATE_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TYPE_PRODUCT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TYPE_RECIPE" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LCN_THAIFULLNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_IDENTIFY_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ADDR_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_SOI_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ROAD_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_MOO_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_THMBL_NAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_AMPHR_NAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_CHWNGNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_TELEPHONE_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_FAX_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_EMAIL_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_IDA_SECOND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCN_THAINAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_THAILASTNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_PREFIXENGCD_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGLASTNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGFULLNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_FLOOR_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_BUILDING_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ZIPCODE_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_HOUSENO_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGADDR_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGMU_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGSOI_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_ENGROAD_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_CHWNG_ENGNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_AMPHR_ENGNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_THMBL_ENGNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_NATIONALITY_CD_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_PREFIXTHAICD_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_PREFIXNAME_SECOND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_ACT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HOSPITAL_CODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MARIJUANA_RENEW" Member="MARIJUANA_RENEWs">
    <Type Name="MARIJUANA_RENEW">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_MARIJUANA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="year" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcnno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="RCVDATE_DISPLAY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CANCEL_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CANCEL_DATE_DISPLAY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LCNNO_DISPLAY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="WORKING_USER_TYPE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_BY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EXP_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EXP_DATE_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="APPROVE_BY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VISITOR_ID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="VISITOR_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_DATE_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ACTIVE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FILE_ATTACH" Member="FILE_ATTACHes">
    <Type Name="FILE_ATTACH">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME_FAKE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NAME_REAL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PATH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EXTENSION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LCNTPCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOG_NUMBER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACTIVE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MAS_TEMPLATE_PROCESS" Member="MAS_TEMPLATE_PROCESSes">
    <Type Name="MAS_TEMPLATE_PROCESS">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROCESS_ID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LCNTYPECD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GROUPS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PREVIEW" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PDF_TEMPLATE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_PATH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PDF_OUTPUT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOG_ERROR" Member="LOG_ERRORs">
    <Type Name="LOG_ERROR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FUNCTION_ERROR_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>